### ISSUE TITLE
[Question] What is the idea behind mutable filter objects?

### ISSUE THREAD

**Issue by dnaber-de** [inpsyde/inpsyde-filter#1]
Just this question to get the idea behind this approach. The mutable state means that a filter object can return different values for the same argument during its life cycle. Further any user of the filter would be able to change the behavior of the filter. Is that desired?

**Comment by Chrico** [comment]
Yes and no. This is currently just a design decision. I just wanted to ensure, that a Filter just filters a value for a given configuration. Changing the configuration after the object is created _could_ maybe lead to unwanted results:

``` php
$filter = new Inpsyde\Filter\DateTime( [ 'format' => 'd.m.Y' ] );

// some other code

// set_options is changed to "public" instead "protected"
$filter->set_options( [ 'format' => 'Y-m-d' ] );

// some more code

$value = $filter->filter( '1464942173' ); 
// results in 2016-06-03 but we wanted 03.06.2106
```

Maybe this is just bad code when someone changes the options to a not wanted format.

If nothing speaks against it, we could easily change the `set_options`-method to `public` to achieve the mutable behavior.

**Comment by dnaber-de** [comment]
Never mind. My bad. It points out that I'm unable to read code after 10. I missed the `protected` in the `AbstractFilter::set_options()`, so the objects actually _are_ immutable which should be the desired behavior. Let's close this ticket and move on :rocket:
