### ISSUE TITLE
Inherited `@uses` documentation

### ISSUE THREAD

**Issue by GaryJones** [inpsyde/inpsyde-filter#3]
Each filter class's `filter()` method aims to inherit the docs from the `AbstractFilter` class's abstract `filter()` method.

However, not all of the filter classes use `_doing_it_wrong()` as the `@uses` suggests.

**Comment by Chrico** [comment]
Hwody @GaryJones 

Yep that right. Should be `@maybe-uses` :) We've to remove this and add it only to the related classes where it's actually used.
